# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import sistema_pb2 as protos_dot_sistema__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/sistema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrquestradorStub(object):
    """Definição do serviço de tarefas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/Orquestrador/Login',
                request_serializer=protos_dot_sistema__pb2.LoginRequest.SerializeToString,
                response_deserializer=protos_dot_sistema__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.SubmeterTarefa = channel.unary_unary(
                '/Orquestrador/SubmeterTarefa',
                request_serializer=protos_dot_sistema__pb2.TarefaRequest.SerializeToString,
                response_deserializer=protos_dot_sistema__pb2.TarefaResponse.FromString,
                _registered_method=True)
        self.ConsultarStatus = channel.unary_unary(
                '/Orquestrador/ConsultarStatus',
                request_serializer=protos_dot_sistema__pb2.StatusRequest.SerializeToString,
                response_deserializer=protos_dot_sistema__pb2.StatusResponse.FromString,
                _registered_method=True)


class OrquestradorServicer(object):
    """Definição do serviço de tarefas
    """

    def Login(self, request, context):
        """Login simples para receber um token [cite: 76]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmeterTarefa(self, request, context):
        """Submissão de tarefas por clientes autenticados [cite: 18, 44]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarStatus(self, request, context):
        """Consulta de status em tempo real [cite: 45]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrquestradorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protos_dot_sistema__pb2.LoginRequest.FromString,
                    response_serializer=protos_dot_sistema__pb2.TokenResponse.SerializeToString,
            ),
            'SubmeterTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmeterTarefa,
                    request_deserializer=protos_dot_sistema__pb2.TarefaRequest.FromString,
                    response_serializer=protos_dot_sistema__pb2.TarefaResponse.SerializeToString,
            ),
            'ConsultarStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarStatus,
                    request_deserializer=protos_dot_sistema__pb2.StatusRequest.FromString,
                    response_serializer=protos_dot_sistema__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Orquestrador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Orquestrador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orquestrador(object):
    """Definição do serviço de tarefas
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orquestrador/Login',
            protos_dot_sistema__pb2.LoginRequest.SerializeToString,
            protos_dot_sistema__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmeterTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orquestrador/SubmeterTarefa',
            protos_dot_sistema__pb2.TarefaRequest.SerializeToString,
            protos_dot_sistema__pb2.TarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Orquestrador/ConsultarStatus',
            protos_dot_sistema__pb2.StatusRequest.SerializeToString,
            protos_dot_sistema__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
