# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/sistema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/sistema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/sistema.proto\".\n\x0cLoginRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\"/\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\"G\n\rTarefaRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x14\n\x0ctempo_logico\x18\x03 \x01(\x05\"5\n\x0eTarefaResponse\x12\x11\n\tid_tarefa\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"\"\n\rStatusRequest\x12\x11\n\tid_tarefa\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9d\x01\n\x0cOrquestrador\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.TokenResponse\x12\x31\n\x0eSubmeterTarefa\x12\x0e.TarefaRequest\x1a\x0f.TarefaResponse\x12\x32\n\x0f\x43onsultarStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sistema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=24
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_TOKENRESPONSE']._serialized_start=72
  _globals['_TOKENRESPONSE']._serialized_end=119
  _globals['_TAREFAREQUEST']._serialized_start=121
  _globals['_TAREFAREQUEST']._serialized_end=192
  _globals['_TAREFARESPONSE']._serialized_start=194
  _globals['_TAREFARESPONSE']._serialized_end=247
  _globals['_STATUSREQUEST']._serialized_start=249
  _globals['_STATUSREQUEST']._serialized_end=283
  _globals['_STATUSRESPONSE']._serialized_start=285
  _globals['_STATUSRESPONSE']._serialized_end=317
  _globals['_ORQUESTRADOR']._serialized_start=320
  _globals['_ORQUESTRADOR']._serialized_end=477
# @@protoc_insertion_point(module_scope)
